#ifndef __BSP_MAIN_H
#define __BSP_MAIN_H


/*清扫时，电机转速，PWM占空比*/
typedef enum
{
	BRUSHMOTORRPM  = 2000 ,
	ROLLMOTORRPM   = 2000 ,
	MOTORSPEED     = 200  
}MotorCleanPWM;

/*反馈电压最大值*/
typedef enum
{
	ROLLER_MOTOR_MAX_ADC_VALUE 	 = 4000,
	BRUSH_MOTOR_MAX_ADC_VALUE 	 = 4000,
	VACUUM_MOTOR_MAX_ADC_VALUE 	 = 4000,
	ROBOT_BATTERY_MIN_ADC_VALUE  = 2000,
	WHEEL_MOTOR_MAX_ADC_VALUE 	 = 4000,
	MAXCLIFFADCDT                =  80
}MAX_Voltage;


/*运行状态*/
typedef enum
{
	ROBOT_STATE_INIT       = 0,
	ROBOT_STATE_STANDBY    ,
	ROBOT_STATE_WORKING    ,
	ROBOT_STATE_SUSPEND    ,
	ROBOT_STATE_CHARGING   ,
	ROBOT_STATE_DEFAULT    

}RunState;

/*清扫方式*/
typedef enum
{
	ROBOT_WORKWAY_HOME     = 0,
	ROBOT_WORKWAY_CLEAN    ,
	ROBOT_WORKWAY_CHARGE   ,
	ROBOT_WORKWAY_DEFAULT 
}WorkMethod;

/*按键序号*/
typedef enum
{
	ROBOT_CONTROL_KEY  = 0,
	ROBOT_CONTROL_APP  ,
	ROBOT_CONTROL_BOT3 
}KeySN;

/*错误码*/
typedef enum
{
	ROBOT_ERROR_NUM_CLIF          = 0,
	ROBOT_ERROR_NUM_LEFT_WHEEL    ,
	ROBOT_ERROR_NUM_RIGHT_WHEEL   ,
	ROBOT_ERROR_NUM_ROLLER_MOTOR  ,
	ROBOT_ERROR_NUM_BRUSH_MOTOR   ,
	ROBOT_ERROR_NUM_VACUUM_MOTOR  ,
	ROBOT_ERROR_NUM_OFFLANDR      ,
	ROBOT_ERROR_NUM_OFFLANDL      ,
	ROBOT_ERROR_NUM_BATTERY       ,
	ROBOT_ERROR_NUM_BUMPER        ,
	ROBOT_ERROR_NUM_DUST_HALL     ,
	ROBOT_ERROR_NUM_DEFAULT       
}ErrorSN;

#endif

